name: Jira issues graph
on:
  push:
  schedule:
    - cron: "0 * * * *" # @hourly
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Start MySQL
        run: sudo systemctl start mysql.service # user:root password:root
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Update graph
        run: python3 graph-hustle.py
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      - name: Install npm
          run: npm install
      - name: Dynamo put
          run: node ddb.js
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Hourly update
